version: 2.1

executors:
  default-exec:
    docker:
      - image: 'circleci/node:latest'

jobs:
  test:
    executor: default-exec
    steps:
      - checkout 
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: 
          name: Install packages
          command: npm install
      - save_cache:
          # save cache
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Run test with Jest
          command: npm run test

workflows:
  run_test:
    jobs:
      - test